name: crop_yield_dss
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: dss_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dss_db
    volumes:
      - ./database/init_postgis.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dss_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  minio:
    image: quay.io/minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: minio_s3
    restart: always
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  geo_api:
    build:
      context: .
      dockerfile: geo_api/Dockerfile
      network: host
    image: crop-yield-dss-geo_api
    container_name: geo_api
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@postgres/dss_db
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "8000:8000"

  ml_api:
    build:
      context: .
      dockerfile: ml_api/Dockerfile
      network: host
    image: crop-yield-dss-ml_api
    container_name: ml_api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"

  dis:
    build:
      context: .
      dockerfile: dis/Dockerfile
      network: host
    image: crop-yield-dss-dis
    container_name: dis_service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8002:8000"

  frontend:
    build:
      context: ./frontend
      network: host
    image: crop_yield_dss-frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true   # <--- Add this one too
      - WDS_SOCKET_PORT=0        # Prevents WebSocket connection errors
      - VITE_GEO_API_URL=http://localhost:8000/v1
    depends_on:
      - geo_api

volumes:
  minio_data: