services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: dss_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dss_db
    volumes:
      - ./database/init_postgis.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dss_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  minio:
    image: quay.io/minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: minio_s3
    restart: always
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  geo-api:
    build:
      context: .
      dockerfile: geo-api/Dockerfile
      network: host
    image: crop-yield-dss-geo-api # Explicit name
    container_name: geo_api
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@postgres/dss_db
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "8000:8000"

  ml-api:
    build:
      context: .
      dockerfile: ml-api/Dockerfile
      network: host
    image: crop-yield-dss-ml-api
    container_name: ml_api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"

  dis:
    build:
      context: .
      dockerfile: dis/Dockerfile
      network: host
    image: crop-yield-dss-dis
    container_name: dis_service
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "8002:8000"

frontend:
    build:
      context: ./frontend
      network: host
    container_name: frontend_app
    ports:
      - "3000:3000"  
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - geo-api
      - ml-api
      - dis
volumes:
  minio_data: